<?php

namespace AppBundle\Repository;

/**
 * CompetitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetitionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get the homepage's query
     *
     * @return \Doctrine\ORM\Query
     */
    public function getIndexQuery()
    {
        $qb = $this->createQueryBuilder('c')
                   ->orderBy('c.created', 'ASC');

        return $qb->getQuery();
    }
}
