<?php

namespace AppBundle\Repository;

/**
 * CompetitionMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetitionMessageRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get view query
     *
     * @parameter integer $competitionId
     * @return \Doctrine\ORM\Query
     */
    public function getViewQuery($competitionId)
    {
        $qb = $this->createQueryBuilder('m')
                   ->where('m.competition = :competitionId')
                   ->setParameter('competitionId', $competitionId)
                   ->orderBy('m.created', 'DESC');

        return $qb->getQuery();
    }
}
