<?php

namespace AppBundle\Repository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderByPriorityAndPublished()
    {
        $qb = $this->createQueryBuilder('p')
            ->where('p.published = 1')
            ->orderBy('p.priority', 'ASC');

        return $qb->getQuery()->getResult();
    }

    public function findAllOrderByPriority()
    {
        $qb = $this->createQueryBuilder('p')
            ->orderBy('p.priority', 'ASC');

        return $qb->getQuery()->getResult();
    }
}
