<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get the homepage's query.
     *
     * @return \Doctrine\ORM\Query
     */
    public function getIndexQuery()
    {
        $qb = $this->createQueryBuilder('p')
                   ->where('p.published = 1')
                   ->orderBy('p.created', 'DESC');

        return $qb->getQuery();
    }

    /**
     * Get category's query
     *
     * @param integer $id
     * @return \Doctrine\ORM\Query
     */
    public function getCategoryQuery($id)
    {
        $qb = $this->createQueryBuilder('p')
                   ->leftJoin('p.categories', 'c')
                   ->where('c.id = :id')
                   ->andWhere('p.published = 1')
                   ->orderBy('p.created', 'DESC')
                   ->setParameter('id', $id);

        return $qb->getQuery();
    }
}
