<?php

namespace UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get users who want receive an email when a competition is created
     *
     * @return array
     */
    public function findUserWhenCompetitionCreated($id)
    {
        $qb = $this->createQueryBuilder('u')
                   ->where('u.emailOnCompetitionCreated = 1')
                   ->andWhere('u.id <> :id')
                   ->setParameter('id', $id);

        return $qb->getQuery()->getResult();
    }
}
